name: Deploy

on: 
    push:
        # 只有master分支发生push事件时，才会触发workflow
        branches: [main]
        
env:
    SECRET: ${{ secrets.ALI_TOKEN }}
    cache-name: note


jobs: 
  buildAndDeploy:
     runs-on: ubuntu-latest
     steps:
            - uses: actions/checkout@master

            - uses: actions/setup-node@v1
              with:
                  node-version: v16.0.0

            #缓存依赖
            - name: Cache nodemodules
              uses: actions/cache@v1
              env:
                  cache-name: cache-node-modules
              with:
                  # 需要缓存的文件的路径
                  path: ./node_modules 
                  # 对缓存的文件指定的唯一标识
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
                  # 用于没有再找目标key的缓存的backup选项
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # 装依赖
            - name: Install
              run: yarn

            # 打包
            - name: Build
              run: yarn docs:build
                
            # 上传打包
            - name: Rsync Deployments Action
              uses: Burnett01/rsync-deployments@5.2.1
              with:
                switches: -avzr --delete
                path: docs/.vuepress/dist/
                remote_path: /var/www/html/site/HIDETOXIC/docs/dist/
                remote_host: 47.111.154.112
                remote_user: root
                remote_key: ${{ secrets.SECRET }}
